# Generated by Django 4.1.1 on 2023-07-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_image_image_alter_image_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
