# Generated by Django 4.1.1 on 2023-07-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productoldprice',
            field=models.FloatField(default=0),
        ),
    ]
