# Generated by Django 4.1.1 on 2023-08-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
