# Generated by Django 4.1.1 on 2023-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_product_slug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pcomment',
            field=models.TextField(),
        ),
    ]
