# Generated by Django 4.1.1 on 2023-08-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiew',
            new_name='Review',
        ),
    ]
