# Generated by Django 4.1.1 on 2023-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_rename_rewiew_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='star5',
            field=models.IntegerField(default=0),
        ),
    ]
