# Generated by Django 4.1.1 on 2023-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_product_star1_product_star2_product_star3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productrating',
            field=models.FloatField(default=0),
        ),
    ]
