# Generated by Django 4.1.1 on 2023-08-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_product_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productrating',
            field=models.IntegerField(default=0),
        ),
    ]
