# Generated by Django 4.1.1 on 2023-08-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_product_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productratingcount',
            field=models.IntegerField(default=0),
        ),
    ]
