# Generated by Django 4.1.1 on 2023-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_remove_product_webapp_prod_product_8c50f0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productcategory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=255),
        ),
    ]
