# Generated by Django 4.1.1 on 2023-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
