# Generated by Django 4.1.1 on 2023-10-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_alter_product_productcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productcards',
            field=models.JSONField(),
        ),
    ]
