# Generated by Django 4.1.1 on 2023-10-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_alter_product_productcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productcards',
            field=models.CharField(default='', max_length=255),
        ),
    ]
