# Generated by Django 4.1.1 on 2023-10-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_alter_product_productcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
