# Generated by Django 5.0.3 on 2024-07-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_alter_product_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star5',
        ),
    ]
