# Generated by Django 5.0.3 on 2024-07-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_remove_product_star1_remove_product_star2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productrating',
            field=models.FloatField(default=0),
        ),
    ]
