# Generated by Django 5.0.3 on 2024-07-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_remove_product_productrating_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='productrating',
        ),
    ]
